"""Train and export a local TF-IDF + Logistic Regression model.

How to retrain:
1. Add labeled examples to training/data.csv with columns: text,label
2. Install dependencies in your Python environment:
   python -m pip install scikit-learn pandas
3. Run this script from the extension root:
   python training/train_model.py
4. Reload the unpacked Chrome extension so it uses the new model/model.json

The exported JSON format is intentionally simple so classifier.js can run the
model locally in a content script without TensorFlow.js, ONNX, or a backend.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "training" / "data.csv"
MODEL_PATH = ROOT / "model" / "model.json"

LABEL_ORDER = [
    "safe",
    "urgency",
    "scarcity",
    "confirmshaming",
    "forced_action",
    "hidden_costs",
    "misleading_cta",
]


def train_model() -> dict:
    data = pd.read_csv(DATA_PATH)

    missing_columns = {"text", "label"} - set(data.columns)
    if missing_columns:
        raise ValueError(f"training/data.csv is missing columns: {sorted(missing_columns)}")

    unknown_labels = sorted(set(data["label"]) - set(LABEL_ORDER))
    if unknown_labels:
        raise ValueError(f"Unknown labels in training data: {unknown_labels}")

    pipeline = Pipeline(
        steps=[
            (
                "tfidf",
                TfidfVectorizer(
                    lowercase=True,
                    token_pattern=r"(?u)\b[a-zA-Z0-9']{2,}\b",
                    norm=None,
                    use_idf=True,
                    smooth_idf=True,
                ),
            ),
            (
                "classifier",
                LogisticRegression(
                    max_iter=1000,
                    multi_class="auto",
                    class_weight="balanced",
                    random_state=42,
                ),
            ),
        ]
    )

    pipeline.fit(data["text"], data["label"])

    vectorizer: TfidfVectorizer = pipeline.named_steps["tfidf"]
    classifier: LogisticRegression = pipeline.named_steps["classifier"]

    feature_names = vectorizer.get_feature_names_out().tolist()
    class_to_row = {label: index for index, label in enumerate(classifier.classes_)}

    weights = []
    bias = []
    for label in LABEL_ORDER:
        row_index = class_to_row[label]
        weights.append(classifier.coef_[row_index].tolist())
        bias.append(float(classifier.intercept_[row_index]))

    return {
        "modelType": "tfidf_logistic_regression",
        "version": "trained-local-demo",
        "labels": LABEL_ORDER,
        "vocabulary": feature_names,
        "idf": vectorizer.idf_.tolist(),
        "weights": weights,
        "bias": bias,
        "preprocessing": {
            "lowercase": True,
            "collapseWhitespace": True,
            "tokenPattern": "[a-z0-9']+",
            "minTokenLength": 2,
        },
        "notes": "Generated by training/train_model.py from training/data.csv.",
    }


def main() -> None:
    model = train_model()
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_PATH.write_text(json.dumps(model, indent=2), encoding="utf-8")
    print(f"Wrote {MODEL_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
